-- Recipe ingestion pipeline schema
-- 新增原始采集表、结构化事实表、前端详情表

CREATE TABLE IF NOT EXISTS `recipe_source_records` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `source_site` VARCHAR(50) NOT NULL COMMENT '来源站点，如 IBA',
    `source_url` VARCHAR(255) NOT NULL COMMENT '来源详情页 URL',
    `page_type` VARCHAR(20) NOT NULL DEFAULT 'detail' COMMENT '页面类型：list/detail',
    `raw_title` VARCHAR(255) DEFAULT NULL COMMENT '原始页面标题',
    `raw_category` VARCHAR(100) DEFAULT NULL COMMENT '原始分类文本',
    `raw_image_url` VARCHAR(255) DEFAULT NULL COMMENT '原始主图地址',
    `raw_ingredients_text` TEXT DEFAULT NULL COMMENT '原始配料文本',
    `raw_method_text` TEXT DEFAULT NULL COMMENT '原始制作方法文本',
    `raw_garnish_text` VARCHAR(255) DEFAULT NULL COMMENT '原始装饰文本',
    `raw_html` LONGTEXT DEFAULT NULL COMMENT '原始 HTML',
    `raw_text` LONGTEXT DEFAULT NULL COMMENT '原始纯文本',
    `status` VARCHAR(20) NOT NULL DEFAULT '已抓取' COMMENT '流程状态：已抓取/已解析/AI已生成/待审核/已发布/已驳回',
    `scraped_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '抓取时间',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_recipe_source_url` (`source_url`),
    KEY `idx_recipe_source_site` (`source_site`),
    KEY `idx_recipe_source_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `recipe_structured_records` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `source_record_id` BIGINT NOT NULL COMMENT '对应原始采集记录',
    `recipe_key` VARCHAR(64) NOT NULL COMMENT '内部稳定配方标识',
    `english_name` VARCHAR(100) NOT NULL COMMENT '英文名',
    `chinese_name_draft` VARCHAR(100) DEFAULT NULL COMMENT '中文名草稿',
    `category` VARCHAR(100) DEFAULT NULL COMMENT '标准化分类',
    `hero_image` VARCHAR(255) DEFAULT NULL COMMENT '主图地址',
    `garnish` VARCHAR(100) DEFAULT NULL COMMENT '装饰',
    `glass_draft` VARCHAR(100) DEFAULT NULL COMMENT '杯型草稿',
    `method_text` TEXT DEFAULT NULL COMMENT '标准化制作方法文本',
    `ingredients_json` LONGTEXT NOT NULL COMMENT '结构化原料 JSON',
    `steps_json` LONGTEXT NOT NULL COMMENT '结构化步骤 JSON',
    `estimated_abv` VARCHAR(20) DEFAULT NULL COMMENT '估算酒精度',
    `estimated_volume` VARCHAR(20) DEFAULT NULL COMMENT '估算容量',
    `parse_notes` TEXT DEFAULT NULL COMMENT '解析备注',
    `status` VARCHAR(20) NOT NULL DEFAULT '已解析' COMMENT '流程状态：已抓取/已解析/AI已生成/待审核/已发布/已驳回',
    `parsed_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '解析时间',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_recipe_structured_source_record` (`source_record_id`),
    UNIQUE KEY `uk_recipe_structured_recipe_key` (`recipe_key`),
    KEY `idx_recipe_structured_status` (`status`),
    CONSTRAINT `fk_recipe_structured_source`
        FOREIGN KEY (`source_record_id`) REFERENCES `recipe_source_records`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `recipe_detail_contents` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `structured_record_id` BIGINT NOT NULL COMMENT '对应结构化事实记录',
    `recipe_key` VARCHAR(64) NOT NULL COMMENT '内部稳定配方标识',
    `name` VARCHAR(50) NOT NULL COMMENT '中文名',
    `english_name` VARCHAR(100) DEFAULT NULL COMMENT '英文名',
    `category` VARCHAR(50) NOT NULL COMMENT '配方分类',
    `hero_image` VARCHAR(255) NOT NULL COMMENT '顶部主图地址',
    `highlight` VARCHAR(100) DEFAULT NULL COMMENT '顶部强调文案',
    `subtitle` VARCHAR(150) NOT NULL COMMENT '主图下的一句话介绍',
    `description` VARCHAR(255) NOT NULL COMMENT '配方简介',
    `story` VARCHAR(255) DEFAULT NULL COMMENT '场景化描述',
    `best_for` VARCHAR(100) NOT NULL COMMENT '适合场景',
    `difficulty` VARCHAR(20) NOT NULL COMMENT '制作难度',
    `duration` VARCHAR(20) NOT NULL COMMENT '制作时长',
    `abv` VARCHAR(20) NOT NULL COMMENT '酒精度展示值',
    `volume` VARCHAR(20) NOT NULL COMMENT '出杯容量展示值',
    `glass` VARCHAR(100) NOT NULL COMMENT '建议杯型',
    `garnish` VARCHAR(100) NOT NULL COMMENT '装饰物',
    `serve_temperature` VARCHAR(50) NOT NULL COMMENT '饮用温度',
    `flavor_tags_json` TEXT NOT NULL COMMENT '风味标签 JSON',
    `flavor_metrics_json` TEXT NOT NULL COMMENT '风味维度 JSON',
    `pairings_json` TEXT DEFAULT NULL COMMENT '搭配建议 JSON',
    `service_notes_json` TEXT DEFAULT NULL COMMENT '饮用提示 JSON',
    `ingredients_json` LONGTEXT NOT NULL COMMENT '前端配料 JSON',
    `steps_json` LONGTEXT NOT NULL COMMENT '前端步骤 JSON',
    `source_site` VARCHAR(50) DEFAULT NULL COMMENT '来源站点',
    `source_url` VARCHAR(255) DEFAULT NULL COMMENT '来源链接',
    `status` VARCHAR(20) NOT NULL DEFAULT '待审核' COMMENT '流程状态：已抓取/已解析/AI已生成/待审核/已发布/已驳回',
    `ai_generated_at` DATETIME DEFAULT NULL COMMENT 'AI 生成时间',
    `reviewed_at` DATETIME DEFAULT NULL COMMENT '审核时间',
    `published_at` DATETIME DEFAULT NULL COMMENT '发布时间',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_recipe_detail_structured_record` (`structured_record_id`),
    UNIQUE KEY `uk_recipe_detail_recipe_key` (`recipe_key`),
    KEY `idx_recipe_detail_status` (`status`),
    CONSTRAINT `fk_recipe_detail_structured`
        FOREIGN KEY (`structured_record_id`) REFERENCES `recipe_structured_records`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
